backend:
  name: github
  repo: davidroberts63/teapotcoder
  branch: cmstest

media_folder: source/images
public_folder: /images

collections:
  - name: post
    label: Post
    folder: source/_posts
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}