backend:
  name: git-gateway
  repo: davidroberts63/teapotcoder
  branch: cmstest

media_folder: source/images
public_folder: /images

collections:
  - name: post
    label: Post
    folder: source/_posts
    extension: md
    create: true
    fields:
      - {name: "title", label: "Title"}
      - {name: "date", label: "Date", widget: "datetime"}
      - {name: "tags", label: "Tags", widget: "string"}
      - {name: "body", label: "Body", widget: "markdown"}