# Header
menu:
  Home: /
  Archives: /archives
	Failures: /page/failures/
  About: /page/about-me/
rss:
github: https://github.com/davidroberts63

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- recent_posts
- archive
- tag

# Links
links:

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: davidroberts63
google_plus:
fb_admins:
fb_app_id:
