# Header
menu:
  Home: /
  Archives: /archives
	Failures: /page/failures/
  About: /page/about-me/
github: https://github.com/davidroberts63

# Content
excerpt_link: false
fancybox: true

# Sidebar
sidebar: left
widgets:
- recent_posts
- tag

# Links
links:

# Miscellaneous
google_analytics: UA-44834504-1
favicon: /images/favicon.png
twitter: davidroberts63
google_plus:
fb_admins:
fb_app_id:
rss: /feed.xml
